services:
  frontend:
    image: ghcr.io/dainst/arachne4-frontend:${ARACHNE_FRONTEND_IMAGE_VERSION}
    volumes:
      - ${ARCHAEOCLOUD_PATH}:/media/archaeocloud
      - /opt/arachne_sitemap:/var/www/sitemap
      - /opt/robots:/var/www/robots
      - /var/log/nginx:/var/log/nginx:rw
    labels:
      - traefik.enable=true
      - traefik.port=80

      - traefik.http.routers.frontend.rule=Host(`${SERVER_ADDRESS}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=myresolver
      - traefik.http.middlewares.frontend-compress.compress=true
      - traefik.http.routers.frontend.middlewares=frontend-compress,realip,anubis@docker

      # This block should only be added in the `stable` branch/be active on the production server.
      #      - traefik.http.middlewares.alt-redirect.redirectregex.regex=.*
      #      - traefik.http.middlewares.alt-redirect.redirectregex.replacement=https://arachne.dainst.org
      #      - traefik.http.routers.alt.middlewares=alt-redirect
      #      - traefik.http.routers.alt.rule=Host(`objects.idai.world`)
      #      - traefik.http.routers.alt.tls.certresolver=myresolver
      #      - traefik.http.routers.alt.entrypoints=websecure
      # ^- end of production only block

      - "com.centurylinklabs.watchtower.enable=true"
    user: "${UID}:${GID}"
    restart: always

  backend:
    image: ghcr.io/dainst/arachne4-backend:${ARACHNE_BACKEND_IMAGE_VERSION}
    environment:
      - "DB_SERVER=${SERVER_ADDRESS}:3306"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "SERVER_ADDRESS=${SERVER_ADDRESS}"
      - "SMTP_USER_NAME=${SMTP_USER_NAME}"
      - "SMTP_USER_PASSWORD=${SMTP_USER_PASSWORD}"
      - "IIPIMAGE_SERVER=frontend"
      - "ELASTICSEARCH_SERVER=elasticsearch"
    volumes:
      - ${ARCHAEOCLOUD_PATH}:/media/archaeocloud
      - ${ARACHNE4_IMAGE_CACHE_PATH}:/tmp/arachne4ImageCache
    hostname: "${HOST_NAME}"
    user: "${UID}:${GID}"
    labels:
      - traefik.enable=false
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

  db:
    image: mariadb:latest
    container_name: arachne4_db
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=arachne"
      - "MYSQL_USER=arachne"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    command: --innodb-log-file-size=256M --innodb_buffer_pool_size=12G --innodb_strict_mode=off --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin:apache
    environment:
      - "PMA_HOST=arachne4_db"
      - "PMA_ABSOLUTE_URI=https://${SERVER_ADDRESS}/phpmyadmin/"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`${SERVER_ADDRESS}`) && PathPrefix(`/phpmyadmin`)
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.tls.certresolver=myresolver
      - traefik.http.middlewares.phpmyadmin-strip.stripprefix.prefixes=/phpmyadmin
      - traefik.http.middlewares.phpmyadmin-ipwhitelist.ipwhitelist.sourcerange=134.95.0.0/16,172.28.0.0/20,195.37.61.194,195.37.61.201,172.18.0.0/16,77.39.225.242,77.39.225.250,213.233.42.42
      - traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-strip,phpmyadmin-ipwhitelist
      - traefik.port=80
    restart: always

  elasticsearch:
    image: ghcr.io/dainst/arachne4-elastic-search:${ELASTIC_SEARCH_VERSION}
    environment:
      - discovery.type=single-node
      - cluster.name=arachne4
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always

  iipimage:
    image: ghcr.io/dainst/arachne4-image-server:${IMAGE_SERVER_VERSION}
    volumes:
      - ${ARCHAEOCLOUD_PATH}:/media/archaeocloud
    user: "${UID}:${GID}"
    restart: always

  aiax:
    image: ghcr.io/dainst/aiax:${AIAX_VERSION}
    volumes:
      - ${AIAX_DATA_DIR}:/var/www/html/aiax/data
    environment:
      - ARACHNE4_BASE_URL=https://${SERVER_ADDRESS}
      - BASE_URL=https://${SERVER_ADDRESS}
      - DB_SERVER=arachne4_db
      - DB_PASSWORD
    labels:
      - traefik.enable=true
      - traefik.http.routers.aiax.rule=Host(`${SERVER_ADDRESS}`) && PathPrefix(`/aiax`)
      - traefik.http.routers.aiax.entrypoints=websecure
      - traefik.http.routers.aiax.tls.certresolver=myresolver
      - traefik.port=80
      - com.centurylinklabs.watchtower.enable=true
    user: "${UID}:${GID}"
    restart: always

  hac_via:
    image: ghcr.io/dainst/hac_via:${HAC_VIA_VERSION}
    volumes:
      - ${HAC_VIA_ARCHIVE_DIR}:/archive
      - ${HAC_VIA_PREVIEW_DIR}:/previews
      - ${HAC_VIA_STAGING_DIR}:/staging
      - ${HAC_VIA_TAPE_DIR}:/tape_dir
      - ${ARCHAEOCLOUD_PATH}/aronscans/objectscans/:/published_jpg
      - ${ARCHAEOCLOUD_PATH}/S-Arachne/arachne4scans/arachne4webimages/objectscans/:/published_ptif
    environment:
      - PHX_HOST=images.${SERVER_ADDRESS}
      - DATABASE_NAME=arachne
      - DATABASE_USER=arachne
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=arachne4_db
      - SECRET_KEY_BASE=${HAC_VIA_KEY_BASE}
      - ARACHNE_BASE_URL=https://${SERVER_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.hac_via.rule=Host(`images.${SERVER_ADDRESS}`)
      - traefik.http.routers.hac_via.entrypoints=websecure
      - traefik.http.routers.hac_via.tls.certresolver=myresolver
      - traefik.http.services.hac_via.loadbalancer.server.port=4000
    restart: always

  anubis:
    image: ghcr.io/techarohq/anubis:v1.25.0
    restart: unless-stopped
    environment:
      TARGET: " "
      BIND: ":8080"
      REDIRECT_DOMAINS: ${SERVER_ADDRESS}
      PUBLIC_URL: "https://anubis.${SERVER_ADDRESS}"
      COOKIE_DOMAIN: ${SERVER_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.anubis.rule=Host(`anubis.${SERVER_ADDRESS}`)
      - traefik.http.routers.anubis.entrypoints=websecure
      - traefik.http.routers.anubis.tls.certresolver=myresolver
      - traefik.http.services.anubis.loadbalancer.server.port=8080 # Telling Traefik where to receive requests
      - traefik.http.routers.anubis.service=anubis # Telling Traefik to use the above specified port

  traefik:
    image: traefik:v3.6
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=dev@dainst.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.anubis.forwardauth.address=http://anubis:8080/.within.website/x/cmd/anubis/api/check
      - traefik.http.middlewares.realip.headers.customRequestHeaders.X-Forwarded-For=>CF-Connecting-IP

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 60
    restart: always

volumes:
  elasticsearch_data:
